// reactFiles/components/FileListItem.jsx
import printJS from "print-js";
import Icon from "@mdi/react";
import { mdiEye, mdiFileDownload, mdiPrinter } from "@mdi/js";
import "./loader.css";

const FileListItem = ({
  file,
  download,
  handleFileConvert,
  progress,
  handlePreview,
}) => {
  let fileSize;
  if (file.size > 1000000) {
    fileSize = `${(file.size / 1000 / 1000).toFixed(1)} MB`;
  } else {
    fileSize = `${Math.round(file.size / 1000)} KB`;
  }

  const id = "one";

  const handlePrint = () => {
    if (download) printJS(download.url);
  };

  return (
    <div className="list-row">
      <p className="fileName">{file.name}</p>
      <p className="fileSize italic">{fileSize}</p>
      {!download && !progress && (
        <button
          className="convert_button color-blue"
          onClick={handleFileConvert}
        >
          Lag Hefte
        </button>
      )}
      {!download && progress && <span className="loader"></span>}
      {download && (
        <>
          <a
            className="download_button"
            href={download.url}
            download={`${download.fileName}-book.pdf`}
          >
            <button className="color-green button">
              <Icon path={mdiFileDownload} title="Last ned" size={1} />
            </button>
          </a>
          <button
            onClick={handlePrint}
            className="print_button color-green button"
          >
            <Icon path={mdiPrinter} title="Skriv ut" size={1} />
          </button>
          <button onClick={handlePreview} className="color-blue button">
            <Icon path={mdiEye} title="Vis pdf" size={1} />
          </button>
        </>
      )}
    </div>
  );
};

export default FileListItem;

// src/lib/FileListItem.svelte
<script>
    import Icon from "$lib/Icon.svelte";
    import { mdiFileDownload, mdiPrinter, mdiEye, mdiDelete } from "@mdi/js";
    import { data } from "$lib/data.svelte.js";
    import { browser } from "$app/environment";
    import { onMount } from "svelte";
    import { handleConvert } from "$lib/handleConvert.js";
    import Loader from "./Loader.svelte";

    let { file, i } = $props();

    let printJS;

    onMount(async () => {
        const p = await import("print-js");
        printJS = p.default;
    });

    const handlePrint = (e) => {
        if (browser && file.download) {
            printJS(file.download.url);
        }
    };
    const handlePreview = (e) => {
        console.log(e);
    };
    const handleDelete = (e) => {
        data.files = data.files.filter((e) => e.key != file.key);
    };
</script>

<div class="list_row" data-key={file.key}>
    <p class="fileName">{file.name}</p>
    {#if file.process == "working"}
        <Loader />
    {:else if file.process == "done"}
        <a
            href={file.download.url}
            download={`${file.fileName}-hefte.pdf`}
            class="download_button"
        >
            <button class="color-green">
                <Icon mdi={mdiFileDownload} />
            </button>
        </a>
        <button onclick={handlePrint} class="color-green print_button">
            <Icon mdi={mdiPrinter} />
        </button>
        <a href={file.download.url} target="_blank" class="preview_button">
            <button onclick={handlePreview} class="color-blue">
                <Icon mdi={mdiEye} />
            </button>
        </a>
        <button onclick={handleDelete} data-key={file.key} class="color-red">
            <Icon mdi={mdiDelete} />
        </button>
    {/if}
</div>

<style>
    .list_row {
        --padding: 1rem;
        padding: var(--padding);
        background-color: var(--color-highlight);
        border-radius: var(--radius);
        gap: 1rem;
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        grid-template-rows: repeat(
            2,
            calc(var(--fs-md) + var(--padding) + var(--padding))
        );
        justify-items: center;
        align-items: center;
    }
</style>
