// src/lib/components/FileListItem.svelte
<script>
    import Icon from "$component/Icon.svelte";
    import { mdiFileDownload, mdiPrinter, mdiEye, mdiDelete } from "@mdi/js";
    import { data } from "$data";
    import { browser } from "$app/environment";
    import { onMount } from "svelte";
    import Loader from "$component/Loader.svelte";

    let { file, i } = $props();

    let printJS;

    onMount(async () => {
        const p = await import("print-js");
        printJS = p.default;
    });

    const handlePrint = (e) => {
        if (browser && file.download) {
            printJS(file.download.url);
        }
    };
    const handlePreview = (e) => {
        console.log(e);
    };
    const handleDelete = (e) => {
        data.files = data.files.filter((e) => e.key != file.key);
    };
</script>

<div
    class="grid grid-cols-4 gap-2 bg-neutral-200 dark:bg-neutral-800 p-5 rounded-sm"
    data-key={file.key}
>
    <p class="col-span-4">{file.name}</p>
    {#if file.process == "working"}
        <Loader />
    {:else if file.process == "done"}
        <a
            href={file.download.url}
            download={`${file.fileName}-hefte.pdf`}
            class="place-self-center"
        >
            <button class="button-green">
                <Icon mdi={mdiFileDownload} />
            </button>
        </a>
        <button onclick={handlePrint} class="button-green place-self-center">
            <Icon mdi={mdiPrinter} />
        </button>
        <a href={file.download.url} target="_blank" class="place-self-center">
            <button onclick={handlePreview} class="button-blue">
                <Icon mdi={mdiEye} />
            </button>
        </a>
        <button
            onclick={handleDelete}
            data-key={file.key}
            class="button-red place-self-center"
        >
            <Icon mdi={mdiDelete} />
        </button>
    {/if}
</div>

// src/components/FileListItem.jsx
import printJS from "print-js";
import Icon from "@mdi/react";
import { mdiFileDownload, mdiPrinter } from "@mdi/js";

const FileListItem = ({ file, download, handleFileConvert, progress }) => {
  let fileSize;
  if (file.size > 1000000) {
    fileSize = `${(file.size / 1000 / 1000).toFixed(1)} MB`;
  } else {
    fileSize = `${Math.round(file.size / 1000)} KB`;
  }

  const id = "one";

  const handlePrint = () => {
    if (download) printJS(download.url);
  };

  return (
    <div className="list-row">
      <p className="fileName">{file.name}</p>
      <p className="fileSize italic">{fileSize}</p>
      {!download && !progress && (
        <button
          className="convert_button color-blue"
          onClick={handleFileConvert}
        >
          Lag Hefte
        </button>
      )}
      {!download && progress && <span className="loader"></span>}
      {download && (
        <>
          <a
            className="download_button"
            href={download.url}
            download={`${download.fileName}-book.pdf`}
          >
            <button className="color-green button">
              <Icon path={mdiFileDownload} title="Last ned" size={1} />
            </button>
          </a>
          <button
            onClick={handlePrint}
            className="print_button color-green button"
            key={file.name}
          >
            <Icon path={mdiPrinter} title="Skriv ut" size={1} />
          </button>
        </>
      )}
    </div>
  );
};

export default FileListItem;
